audit_header: false
title: Orlando Real Estate Video Blog with Joseph Luzcaj
description: Our mission at C.A.R.E. Network Realty is to be your best resource for Orlando real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The C.A.R.E. Network Realty, your professional Orlando Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Joseph Luzcaj
  title:
  license_number:
  about_markdown: |
    An energetic and positive force for good, with an inspiring mission to change the world! Joseph is a proud father led by faith. He is an Ambassador of Goodwill, Entrepreneur, and mentor.
  brand: C.A.R.E. Network Realty
  brokerage:
  market: Orlando
  address: 7444 Narcoossee Rd Ste 414, Orlando, FL 32822
  phone: 321-888-3114
  phone_type:
  phone2:
  phone2_type:
  email: joseph@carenetwork.com
  url: http://www.carenetworkrealty.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Orlando Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Orlando Home?"
    CTA_text2: "Search the entire MLS for your Orlando home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/joincarenetwork/?ref=br_rs
  linkedin_url: https://www.linkedin.com/in/josephluczaj/
  youtube_url: https://www.youtube.com/channel/UCoz9BcD-Dxaa4uaNeOLQcHA/featured
  twitter_url:
  instagram_url: https://instagram.com/joincarenetwork
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/JosephCareNetwork/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Orlando Real Estate Podcast with Joseph Luzcaj'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Orlando Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from C.A.R.E. Network Realty - your professional Orlando Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Orlando, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Joseph Luzcaj'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Orlando Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#242A35'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#242A35'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
